name: flutter_app_template
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#................ PACKAGES .............#

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1

  # Icons
  cupertino_icons: ^1.0.8

  #state Management
  get: ^4.6.5
  get_storage: ^2.1.1
  iconsax_flutter: ^1.0.1
  carousel_slider: ^5.1.1

#................ PACKAGES END .............#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # ecommerce_app: any
flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS ------------ #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/email_images/
    - assets/icons/categories/
    - assets/images/promotion/
    - assets/images/products/

  #------------ LOCAL FONTS -------- #

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
